# Generated by Django 3.2.6 on 2023-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='chat/'),
        ),
    ]
