# Generated by Django 4.2.1 on 2023-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_room_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(default=None, null=True, upload_to="chat/")),
            ],
        ),
        migrations.RemoveField(
            model_name="room",
            name="image",
        ),
    ]
