# Generated by Django 4.1.2 on 2023-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_image_remove_room_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hotel_Main_Img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
