# Generated by Django 4.1.2 on 2023-07-23 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_hotel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.DeleteModel(
            name="image",
        ),
    ]
